Repository IBM/ibm-crossplane, pull requests merged in 2021-07, with the labels that each got.

#20 ownerReference fix
  RELEASE_VERSION
  internal/controller/apiextensions/composite/reconciler.go
Labels: approved, size/S

#23 Newoperator
  RELEASE_VERSION
  apis/apiextensions/v1/doc.go
  apis/apiextensions/v1beta1/doc.go
  apis/pkg/v1/doc.go
  apis/pkg/v1alpha1/doc.go
  cluster/charts/crossplane/crds/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
  cluster/charts/crossplane/crds/apiextensions.ibm.crossplane.io_compositions.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_configurationrevisions.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_configurations.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_controllerconfigs.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_locks.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_providerrevisions.yaml
  cluster/charts/crossplane/crds/pkg.ibm.crossplane.io_providers.yaml
  cluster/kustomization.yaml
  docs/contributing/provider_development_guide.md
  internal/client/clientset/versioned/typed/apiextensions/v1/apiextensions_client.go
  internal/client/clientset/versioned/typed/apiextensions/v1/fake/fake_compositeresourcedefinition.go
  internal/client/clientset/versioned/typed/apiextensions/v1/fake/fake_composition.go
  internal/client/clientset/versioned/typed/pkg/v1/fake/fake_configuration.go
  internal/client/clientset/versioned/typed/pkg/v1/fake/fake_configurationrevision.go
  internal/client/clientset/versioned/typed/pkg/v1/fake/fake_provider.go
  internal/client/clientset/versioned/typed/pkg/v1/fake/fake_providerrevision.go
  internal/client/clientset/versioned/typed/pkg/v1/pkg_client.go
  internal/client/clientset/versioned/typed/pkg/v1alpha1/fake/fake_controllerconfig.go
  internal/client/clientset/versioned/typed/pkg/v1alpha1/fake/fake_lock.go
  internal/client/clientset/versioned/typed/pkg/v1alpha1/pkg_client.go
Labels: approved, size/XL

#24 Newoperator
  apis/apiextensions/v1/register.go
  apis/apiextensions/v1beta1/register.go
  apis/pkg/meta/v1/doc.go
  apis/pkg/meta/v1/register.go
  apis/pkg/meta/v1alpha1/doc.go
  apis/pkg/meta/v1alpha1/register.go
  apis/pkg/v1/register.go
  apis/pkg/v1alpha1/register.go
  apis/pkg/v1beta1/register.go
Labels: approved, size/S

#26 Actions ci.yml and tag.yml in .github/workflows
  .github/workflows/ci.yml
  .github/workflows/tag.yml
Labels: approved, size/L

#27 Change building images locally to multiarch
  ibm/Makefile.common.mk
Labels: approved, size/S

#30 add provider reading from Configuration labels
  internal/controller/apiextensions/composite/api.go
  internal/controller/apiextensions/composite/api_test.go
Labels: approved, size/M

#31 skip pushing images
  ibm/Makefile.common.mk
Labels: approved, size/M
