Repository IBM/ibm-crossplane, pull requests merged in 2021-09, with the labels that each got.

#39 Fix img.build target causing errors in prow tests
  cluster/images/crossplane/Makefile
Labels: size/XS

#43 Remove permissions for configmaps and leases from ClusterRoles.
  cluster/charts/crossplane/templates/clusterrole.yaml
  cluster/charts/crossplane/templates/rbac-manager-clusterrole.yaml
  cmd/crossplane/core/core.go
Labels: approved, size/M

#42 new client for secrets
  go.sum
  internal/controller/apiextensions/claim/reconciler.go
  internal/controller/apiextensions/claim/reconciler_test.go
  internal/controller/apiextensions/composite/reconciler.go
  internal/controller/apiextensions/composite/reconciler_test.go
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/definition/reconciler_test.go
  internal/controller/apiextensions/offered/reconciler.go
  internal/controller/apiextensions/offered/reconciler_test.go
Labels: approved, size/M

#44 fix for kafkaUser
  internal/controller/apiextensions/composite/composed.go
Labels: approved, size/S

#40 Remove Lock's finalizer when package list is empty
  go.sum
  internal/controller/pkg/resolver/reconciler.go
  internal/controller/pkg/resolver/reconciler_test.go
  internal/controller/pkg/revision/dependency.go
  internal/controller/pkg/revision/dependency_test.go
Labels: approved, size/L

#45 fix for kafkaUser`
  internal/controller/apiextensions/composite/composed.go
Labels: approved, size/S

#46 add new client also for ConnectionDetailsFetcher
  internal/controller/apiextensions/composite/reconciler.go
Labels: size/S

#47 Replace 'fromEnvVar' with image name from env var
  cmd/crossplane/core/core.go
  go.sum
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/manager/reconciler_test.go
Labels: approved, size/L

#48 Fix typo in 'FromEnvVar'
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/manager/reconciler_test.go
Labels: approved, size/S

#49 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS

#50 revert config name
  internal/controller/pkg/manager/reconciler.go
  internal/controller/pkg/manager/reconciler_test.go
Labels: approved, size/S
