Repository IBM/ibm-crossplane, pull requests merged in 2021-11, with the labels that each got.

#58 fix for SA for zen
  internal/xpkg/fetch.go
Labels: approved, lgtm, size/XS

#59 Fix sa zen
  internal/xpkg/fetch.go
Labels: approved, size/S

#61 update version
  RELEASE_VERSION
Labels: approved, size/XS

#62 Cleaning up CRs when deleting Configuration
  internal/controller/apiextensions/offered/reconciler.go
  internal/controller/apiextensions/offered/reconciler_test.go
Labels: size/M
