Repository IBM/ibm-crossplane, pull requests merged in 2021-08, with the labels that each got.

#33 Override targets installing helm
  Makefile
Labels: size/S

#34 Fix HOSTARCH value
  Makefile
Labels: size/XS

#32 comment return on crd apply error
  internal/controller/apiextensions/definition/reconciler.go
  internal/controller/apiextensions/definition/reconciler_test.go
  internal/controller/apiextensions/offered/reconciler.go
  internal/controller/apiextensions/offered/reconciler_test.go
Labels: size/L
