Repository IBM/ibm-crossplane, pull requests merged in 2022-02, with the labels that each got.

#70 Update RELEASE_VERSION
  RELEASE_VERSION
Labels: approved, size/XS

#71 update release version
  RELEASE_VERSION
Labels: size/XS

#73 update go to 1.17.7
  .github/workflows/ci.yml
  apis/apiextensions/v1/zz_generated.deepcopy.go
  apis/apiextensions/v1alpha1/zz_generated.deepcopy.go
  apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  apis/pkg/meta/v1/zz_generated.deepcopy.go
  apis/pkg/meta/v1alpha1/zz_generated.deepcopy.go
  apis/pkg/v1/zz_generated.deepcopy.go
  apis/pkg/v1alpha1/zz_generated.deepcopy.go
  apis/pkg/v1beta1/zz_generated.deepcopy.go
Labels: size/S

#72 update docker cli
  go.mod
  go.sum
Labels: size/XS
